# Project
version=1.0.0
group=com.nyfaria
java_version=17

# Common
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)

# Mod options
mod_name=Nyf's Multiloader
mod_author=Nyfaria
mod_id=nyfsmultiloader
description=Template setup for Nyfs Multiloader Projects
license=ARR
credits=

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Publishing
curseforge_publishing_enabled=false
curseforge_project_id=0
modrinth_publishing_enabled=false
modrinth_project_id=0
dry_run=false